runtests: validate resulting ngc using sai, but don't expect a particular canon output
It's enough to expect the resulting g-coder, expecting resulting canon
doesn't add anything.  But validating that the resulting g-code is
accepted by SAI *is* useful.

diff --git a/test/runtests b/test/runtests
--- a/test/runtests
+++ b/test/runtests
@@ -53,13 +53,10 @@ do_test() {
         fi
     fi
 
-    if [ -f expected.canon ]; then
-        rs274 -t /dev/null -v /dev/null -g result.ngc >| result.canon 2>> stderr
-        diff -u expected.canon result.canon
-        if [ $? -ne 0 ]; then
-            echo "FAILED: unexpected Canon result"
-            return 1
-        fi
+    rs274 -t /dev/null -v /dev/null -g result.ngc >| result.canon 2>> stderr
+    if [ $? -ne 0 ]; then
+        echo "FAILED: resulting g-code rejected by SAI"
+        return 1
     fi
 
     return 0
